<template><div><blockquote>
<p>代码在<a href="https://github.com/rnacentre/WDL_Tools/blob/main/_SeqWell%26DropSeq%26BD/StarSolo_count.wdl" target="_blank" rel="noopener noreferrer">此处</a></p>
</blockquote>
<h2 id="starsolo" tabindex="-1"><a class="header-anchor" href="#starsolo"><span>Starsolo</span></a></h2>
<p>为了便于工作流的可重复性，我们推荐您使用json文件来描述和存档您的实验参数。</p>
<h2 id="写在前面" tabindex="-1"><a class="header-anchor" href="#写在前面"><span>写在前面</span></a></h2>
<p><a href="https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md" target="_blank" rel="noopener noreferrer">Starsolo</a> 是一个内置STAR比对算法的非常优秀的比对工具，理论上来说，它可以实现和Cellranger相同的效果。在我们这里，它被用于分析使用Smart-seq、Drop-seq、seq-well以及BD这些测序技术产生的测序数据。</p>
<blockquote>
<p>Starsolo 和 Cellranger 一样，可以为用户输出表达矩阵文件（h5及h5ad格式）、BAM文件。</p>
</blockquote>
<p>相较于Cellranger，Starsolo的使用方式非常灵活，这里我们只提供一种比较普适的例子。</p>
<p>让我们开始吧！</p>
<h3 id="对于一个典型的starsolo实验-我们的输入部分的json的内容如下" tabindex="-1"><a class="header-anchor" href="#对于一个典型的starsolo实验-我们的输入部分的json的内容如下"><span>对于一个典型的Starsolo实验，我们的输入部分的json的内容如下</span></a></h3>
<blockquote>
<p>这是一个分析seq-well数据的例子，代码中的注释为每个参数提供了快速参考，您可以参考这些注释来设置您的参数。详细的文档在[这里](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf。</p>
</blockquote>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes light-plus aurora-x has-diff vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">{</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">assay</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">SeqWell</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置测序技术</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">barcode_read</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">read1</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的读取位置</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">disk_space</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">300 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置磁盘空间</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">fastq_files</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">this.fastqgz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置fastq文件</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">genome_name</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">hg38_3.0.0</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置参考基因组的名称</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">limitBAMsortRAM</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置bam排序的内存限制</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">memory</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">24 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置内存</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">num_cpu</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#098658;--shiki-dark:#F78C6C"> 8</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置cpu数量</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">outBAMsortingBinsN</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置bam排序的bins数量</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">outSAMtype</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置输出文件的类型</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">reference_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">s3://bioos-wcnjupodeig44rr6t02v0/Example_10X_data/RAW/starsoloref.tar.gz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置参考基因组的压缩包</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">sample_ID</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">this.date</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置样本名称</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloAdapterMismatchesNmax</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置adapter的mismatch最大容忍数量</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloAdapterSequence</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置adapter的序列</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloBarcodeMate</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的读取位置</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloBarcodeReadLength</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的长度</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCBlen</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的长度</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCBmatchWLtype</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的匹配类型</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCBposition</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的位置</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 类似0_0_0_12：从0开始，长度为12</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCBstart</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的开始位置</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCBwhitelist</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置barcode的白名单</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloCellFilter</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置细胞过滤</span></span>
<span class="line diff add"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloFeatures</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">Gene</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置输出文件的属性</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloInputSAMattrBarcodeQual</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置输入文件的barcode质量</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloInputSAMattrBarcodeSeq</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置输入文件的barcode序列</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloMultiMappers</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置多基因映射（当你使用的是10XGenomics的测序技术时，这个参数是必须的，尤其是考虑到多个reads可能映射到同一个基因）</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloOutFormatFeaturesGeneField3</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置输出文件的属性</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloStrand</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置strand</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloType</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI和barcode的类型</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloUMIdedup</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI去重</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloUMIfiltering</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI过滤</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloUMIlen</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI的长度</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloUMIposition</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI的位置</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">soloUMIstart</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 设置UMI的开始位置</span></span>
<span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">}</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>看起来很复杂，但没关系。仔细观察，您会发现，这个json文件的部分参数已经自动设置好了，在大部分情况下，您只需要依次填写您自己的参数即可。并且，这里为了=适配=更多的测序技术，暴露了很多参数，而在大多数情况下，他们中的很多是不需要填写的。
这里 <mark>唯一需要注意</mark> 的是：您需要根据您的测序技术的实际情况对UMI和barcode参数进行设置。</p>
<h2 id="举例" tabindex="-1"><a class="header-anchor" href="#举例"><span>举例</span></a></h2>
<h3 id="seq-well和drop-seq" tabindex="-1"><a class="header-anchor" href="#seq-well和drop-seq"><span>seq-well和drop-seq</span></a></h3>
<p>对于seq-well和drop-seq，他们的参数比较相似，我们直接把他们的需要的参数内置在了工作流文件中。</p>
<blockquote>
<p>具体而言，他们在代码中的表示如下：</p>
</blockquote>
<div class="language-python line-numbers-mode" data-ext="python" data-title="python"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes light-plus aurora-x has-focused-lines vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"># 其它代码</span></span>
<span class="line has-focus"><span style="--shiki-light:#AF00DB;--shiki-dark:#89DDFF">if</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">~</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C">{assay}</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#0000FF;--shiki-dark:#C792EA"> in</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF"> [</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">SeqWell</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">DropSeq</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]:</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 如果您在测序技术中使用了关键词'SeqWell'或'DropSeq'</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--soloType</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">CB_UMI_Simple</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置UMI和barcode的类型</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--soloCBstart</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">1</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置barcode的开始位置</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--soloCBlen</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">12</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置barcode的长度</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--soloUMIstart</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">13</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置UMI的开始位置</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--soloUMIlen</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">8</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置UMI的长度</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--outSAMtype</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF"> [</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">BAM</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">SortedByCoordinate</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置bam的类型</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    args_dict</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">[</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">--outSAMattributes</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#000000;--shiki-dark:#C792EA"> =</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF"> [</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">CR</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">UR</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">CY</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">UY</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">CB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">UB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">]</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置bam的属性</span></span>
<span class="line has-focus"><span style="--shiki-light:#000000;--shiki-dark:#BBBBBB">    barcode_read </span><span style="--shiki-light:#000000;--shiki-dark:#C792EA">=</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> '</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">read1</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">'</span><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"> # 设置barcode的读取位置, seq-well和drop-seq的barcode在read1中。</span></span>
<span class="line"><span style="--shiki-light:#008000;--shiki-light-font-style:inherit;--shiki-dark:#546E7A;--shiki-dark-font-style:italic"># 其它代码</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>正如您所见，对于非10X Genomics的测序技术，Starsolo的参数设置非常简单，只需要设置UMI和barcode的类型、开始位置、长度、以及输出文件的属性即可。</p>
</div></template>


