<template><div><blockquote>
<p><a href="https://github.com/rnacentre/WDL_Tools/tree/main/_CellRanger_VDJ" target="_blank" rel="noopener noreferrer">WDL代码</a></p>
</blockquote>
<h2 id="vdj-seq-make-reference" tabindex="-1"><a class="header-anchor" href="#vdj-seq-make-reference"><span>VDJ-seq make reference</span></a></h2>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes light-plus aurora-x vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">{</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.cellranger_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 10X</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> Genomics软件包路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.disk_space</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">100 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 数据盘尺寸</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.genome</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 参考基因组名</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.input_fasta</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 输入fasta文件路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.input_gtf</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 输入gtf文件路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.memory</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">32 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 内存</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj_create_reference.num_cpu</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#098658;--shiki-dark:#F78C6C"> 8</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> cpu核心数</span></span>
<span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">}</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="vdj-seq-count" tabindex="-1"><a class="header-anchor" href="#vdj-seq-count"><span>VDJ-seq count</span></a></h2>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes light-plus aurora-x vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">{</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.cellranger_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">s3://bioos-wcnjupodeig44rr6t02v0/Example_10X_data/cellranger-7.2.0.tar.gz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 10X</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> Genomics软件包路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.chain</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">auto</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 链类型</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.denovo</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> false</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 如果设置了</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> --denovo，在组装过程中将不使用</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> V(D)J</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 参考序列。</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.disk_space</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">500 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 数据盘尺寸</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.fastq_file_paths</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 输入fastq文件路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.memory</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">120 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 内存</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.num_cpu</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#098658;--shiki-dark:#F78C6C"> 8</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> cpu核心数</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.reference_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">s3://bioos-wcnjupodeig44rr6t02v0/analysis/sco5tra5eig49htini970/cellranger_vdj_create_reference/a37b5d72-994f-49a1-a28f-2569f03448f2/call-run_cellranger_vdj_create_reference/execution/dsadasd_ref.tar.gz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 参考基因组路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">cellranger_vdj.sample_id</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 样本名</span></span>
<span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">}</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><mark>--denovo</mark>
--reference 参数是可选的。如果指定了 --denovo 且未指定 --reference，则必须提--inner_enrichment_primers 参数。--denovo 选项最适合在没有 V(D)J 参考序列的情况下进行完全的 De Novo 组装。如果你有 V(D)J 参考序列，即使使用 --denovo，结果也会相似但稍微较差。</p>
</div></template>


