<template><div><blockquote>
<p><a href="https://github.com/rnacentre/WDL_Tools/tree/main/_SpaceRanger" target="_blank" rel="noopener noreferrer">WDL代码</a>
参数的选择与测序技术<strong>强相关</strong>，请务必在计算前仔细阅读10X官方文档。</p>
</blockquote>
<h2 id="spaceranger-count-参数-注释" tabindex="-1"><a class="header-anchor" href="#spaceranger-count-参数-注释"><span>spaceranger_count 参数 注释</span></a></h2>
<div class="language-json line-numbers-mode" data-ext="json" data-title="json"><button class="copy" title="复制代码" data-copied="已复制"></button><pre class="shiki shiki-themes light-plus aurora-x vp-code" v-pre=""><code><span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">{</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.area</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 区域</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.colorizedimage</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 染色图像</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.cytaimage</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 细胞图像</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.dapi_index</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> dapi</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 索引</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.darkimage</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 暗图像</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.darkimagestr</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 暗图像字符串</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.disk_space</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">500 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 数据盘尺寸</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.fastq_file_paths</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 原始数据文件路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.filter_probes</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> true</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 是否过滤探针</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.image</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 图像</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.loupe_alignment</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> loupe</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 对齐</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.memory</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">120 GB</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 内存</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.num_cpu</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#098658;--shiki-dark:#F78C6C"> 32</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> cpu</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 核心数</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.probe_file</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 探针文件</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.probe_set</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 探针集</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.r1_length</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> r1</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 长度</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.r2_length</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> r2</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 长度</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.reference_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">s3://bioos-wcnjupodeig44rr6t02v0/Example_10X_data/RAW/refdata-cellranger-GRCh38-3.0.0.tar.gz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 参考基因组路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.reorient_images</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> true</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 是否重新对齐图像</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.run_id</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 运行id</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.sample</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 样本</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.secondary</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> false</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 是否进行二级分析</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.slide</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> slide</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> （如果有）</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.slidefile</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 幻灯片文件</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.spaceranger_tar_gz</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">s3://bioos-wcnjupodeig44rr6t02v0/Example_10X_data/spaceranger-3.0.0.tar.gz</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> spaceranger</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 路径</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.spaceranger_version</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF"> "</span><span style="--shiki-light:#A31515;--shiki-dark:#C3E88D">2.1.0</span><span style="--shiki-light:#A31515;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> spaceranger</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 版本</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.target_panel</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">,</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 目标panel</span></span>
<span class="line"><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">  "</span><span style="--shiki-light:#0451A5;--shiki-dark:#C792EA">spaceranger_count.unknown_slide</span><span style="--shiki-light:#0451A5;--shiki-dark:#89DDFF">"</span><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">:</span><span style="--shiki-light:#0000FF;--shiki-dark:#F78C6C"> null</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> #</span><span style="--shiki-light:#CD3131;--shiki-dark:#FF5370"> 未知slide</span></span>
<span class="line"><span style="--shiki-light:#000000;--shiki-dark:#89DDFF">}</span></span></code></pre>

<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


